# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "智瞳微视人工智能实验室"
  [zh.params]
    description = "Site description in Chinese..."
  [[zh.menu.main]]
    name = "主页"
    url = "#hero"
    weight = 5
  [[zh.menu.main]]
    name = "团队"
    url = "member/"
    weight = 10
  [[zh.menu.main]]
    name = "论文"
    url = "publication/"
    weight = 15
  [[zh.menu.main]]
    name = "照片墙"
    url = "gallery/"
    weight = 20
